"""Compose evaluation JSONs into the final comparison report (E-03).

    python -m swe_sr.report --runs runs/<edsr-run> runs/<unet-run> --out docs/RESULTS.md

Builds the comparison table `docs/VALIDATION.md` specifies from evaluation artifacts that
already exist, rather than recomputing anything. That separation matters: the numbers in a
report should be traceable to the evaluation that produced them, and a report generator that
recomputed could silently disagree with the artifact it cites.

Two rules from `CLAUDE.md` are enforced here rather than left to the author:

- **Every number carries its units, aggregation rule, split, and baseline.** The table header and
  a standing caption state all four.
- **Planned numbers are never presented as measured.** Only values present in an evaluation
  artifact are emitted; a missing method produces an explicit gap, not a blank that reads as
  zero.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

MISSING = "n/a"


def _load(run_dir: Path, split: str) -> dict[str, Any] | None:
    path = run_dir / f"evaluation_{split}.json"
    return json.loads(path.read_text()) if path.is_file() else None


def _fresh(run_dir: Path, scenario: str) -> dict[str, Any] | None:
    path = run_dir / f"evaluation_fresh_{scenario}.json"
    return json.loads(path.read_text()) if path.is_file() else None


def _row(name: str, method: dict[str, Any]) -> str:
    aggregate = method["aggregate_macro_mse_normalized"]
    normalized = method["normalized_metrics"]
    physical = method["physical_metrics_si"]
    return (
        f"| {name} | {method['trainable_parameters']:,} | "
        f"{aggregate['mean']:.4f} | "
        f"[{aggregate['ci_low']:.4f}, {aggregate['ci_high']:.4f}] | "
        f"{normalized['rel_l2_eta']:.4f} | {normalized['rel_l2_u']:.4f} | "
        f"{normalized['rel_l2_v']:.4f} | {physical['relative_mass_error']:.4f} | "
        f"{method['seconds_per_frame'] * 1000:.1f} |"
    )


def build_report(run_dirs: list[Path], *, split: str = "test") -> str:
    """Render the report. Raises if no run has an evaluation artifact to cite."""
    reports = [(d, _load(d, split)) for d in run_dirs]
    available = [(d, r) for d, r in reports if r is not None]
    if not available:
        raise FileNotFoundError(
            f"no evaluation_{split}.json found in any of {[str(d) for d in run_dirs]}; "
            "run `python -m swe_sr.evaluate` first"
        )

    first = available[0][1]
    assert first is not None
    stages = {r["stage"] for _, r in available if r}
    lines = [
        "# Results",
        "",
        "Generated by `python -m swe_sr.report` from the evaluation artifacts in each run "
        "directory. Every value below is traceable to an `evaluation_*.json`; nothing here is "
        "recomputed or hand-entered.",
        "",
        "## Provenance",
        "",
        f"- dataset: `{first['dataset_id']}` (pair `{first['pair_id']}`)",
        f"- IC registry hash: `{first['ic_registry_hash']}`",
        f"- split: **{split}**, {first['snapshots']} snapshots over "
        f"{first['trajectories']} trajectories",
        f"- run stages: {', '.join(sorted(stages))}",
    ]
    if stages - {"full"}:
        lines.append(
            f"- **These runs are labelled {', '.join(sorted(stages))}, not `full`.** They are "
            "not the frozen T-03 experiment, which requires I-02 to freeze the manifest, "
            "commit, configs, seed, and metrics first."
        )
    for _, report in available:
        assert report is not None
        lines.append(
            f"- `{report['model']}`: run `{report['run_id']}`, trained at commit "
            f"`{report['trained_at_commit']}`, checkpoint `{report['checkpoint']}`"
        )

    lines += [
        "",
        "## Comparison",
        "",
        "Aggregation: metrics computed per snapshot and per channel, averaged within each "
        "trajectory, then averaged across trajectories with **equal weight**, per "
        "`docs/VALIDATION.md`. The interval is a 95% percentile bootstrap resampling "
        "*trajectories*, not snapshots.",
        "",
        "Units: `normMSE` and `relL2` are dimensionless on channel-normalized fields; "
        "`mass err` is a dimensionless relative error on de-normalized SI fields; `ms/frame` is "
        "wall-clock inference time on the evaluating host.",
        "",
        "Reference: normalized channels have unit variance, so **predicting the channel mean "
        "scores 1.0**. A method near 1.0 carries no information about the target.",
        "",
        "| Method | Params | normMSE | 95% CI | eta relL2 | u relL2 | v relL2 | mass err |"
        " ms/frame |",
        "|---|---:|---:|---|---:|---:|---:|---:|---:|",
    ]

    # Baselines once: they are identical across runs by construction, and repeating them would
    # imply they were measured separately per model.
    baseline_source = available[0][1]
    assert baseline_source is not None
    for name in ("nearest", "bicubic"):
        if name in baseline_source["methods"]:
            lines.append(_row(name, baseline_source["methods"][name]))
    for _, report in available:
        assert report is not None
        model = report["model"]
        if model in report["methods"]:
            lines.append(_row(model, report["methods"][model]))

    lines += ["", "### Paired comparison against bicubic", ""]
    lines += [
        "Paired on the same trajectories, which removes the trajectory-to-trajectory spread "
        "that would otherwise swamp the difference. Negative favours the method; an interval "
        "excluding zero is evidence on this split, not a claim of physical generalization.",
        "",
        "| Method | mean difference | 95% CI | excludes zero |",
        "|---|---:|---|---|",
    ]
    for _, report in available:
        assert report is not None
        for key, comparison in report["paired_bootstrap_vs_bicubic"].items():
            if key.startswith("nearest"):
                continue
            excludes = comparison["ci_high"] < 0 or comparison["ci_low"] > 0
            lines.append(
                f"| {key} | {comparison['mean_difference']:+.4f} | "
                f"[{comparison['ci_low']:+.4f}, {comparison['ci_high']:+.4f}] | "
                f"{'yes' if excludes else 'no'} |"
            )

    lines += _lead_time_section(available)
    lines += _fresh_section(run_dirs)
    lines += [
        "",
        "## Limitations",
        "",
        "- Error grows strongly with lead time because the coarse and fine members of each pair "
        "are **independent** integrations (D002) and progressively decorrelate. Beyond roughly "
        "30 hours the coarse state carries little information about the specific fine "
        "realization, so error there is not recoverable by any method.",
        "- Consequently a single aggregate number mixes a well-posed regime with a partly "
        "unpredictable one. The lead-time table above is the honest reading; the aggregate is a "
        "summary of a mixture.",
        "- No data augmentation is used: reflections and the transpose are not symmetries of a "
        "rotating beta-plane (D018), so the effective training set is the trajectory count "
        "times the number of decorrelated states per trajectory.",
        "- Results are for the tested Gaussian initial-condition family on a closed rotating "
        "basin. No claim of physical generalization beyond it is made.",
    ]
    return "\n".join(lines) + "\n"


def _lead_time_section(available: Sequence[tuple[Path, dict[str, Any]]]) -> list[str]:
    """The stratified table, which the aggregate cannot substitute for."""
    lines = [
        "",
        "## Normalized macro MSE by lead time",
        "",
        "Included because the aggregate hides a regime change: the models are worse than "
        "bicubic at short lead times, where the coarse state nearly determines the fine one, "
        "and much better at long lead times, where it does not.",
        "",
    ]
    first = available[0][1]
    methods = list(first["methods"])
    for _, report in available[1:]:
        if report["model"] not in methods:
            methods.append(report["model"])

    keys = sorted(
        first["methods"][methods[0]]["normalized_macro_mse_by_lead_time_hours"], key=float
    )
    lines.append("| t (h) | " + " | ".join(methods) + " |")
    lines.append("|---:|" + "---:|" * len(methods))
    for key in keys[:: max(1, len(keys) // 14)]:
        row = f"| {float(key):.2f} |"
        for method in methods:
            value = MISSING
            for _, report in available:
                if method in report["methods"]:
                    breakdown = report["methods"][method]["normalized_macro_mse_by_lead_time_hours"]
                    if key in breakdown:
                        value = f"{breakdown[key]:.4f}"
                    break
            row += f" {value} |"
        lines.append(row)
    return lines


def _fresh_section(run_dirs: list[Path]) -> list[str]:
    """Fresh workloads, reported separately and never folded into the test score."""
    rows: list[str] = []
    for run_dir in run_dirs:
        for scenario in ("fresh_id", "ring_ood"):
            report = _fresh(run_dir, scenario)
            if report is None:
                continue
            # Artifacts written before lead-time spans were recorded lack this key. Treat it as
            # an explicit unknown rather than crashing or, worse, quietly implying the span
            # matched: an unverifiable span is exactly what made an earlier fresh comparison
            # misleading.
            lead_time = report.get("lead_time_hours")
            for name, method in report["methods"].items():
                aggregate = method["aggregate_macro_mse_normalized"]
                if lead_time is None:
                    span = MISSING
                    matches = "UNKNOWN - regenerate this artifact"
                else:
                    span = f"{lead_time['first']:.1f}-{lead_time['last']:.1f}"
                    matches = "yes" if lead_time["matches_training_range"] else "NO"
                rows.append(
                    f"| {scenario} | {report['model']} | {name} | {aggregate['mean']:.4f} | "
                    f"[{aggregate['ci_low']:.4f}, {aggregate['ci_high']:.4f}] | "
                    f"{span} | {matches} |"
                )
    if not rows:
        return []
    return [
        "",
        "## Fresh post-training workloads",
        "",
        "Generated after model selection, evaluated without fine-tuning, and using the training "
        "split's normalization. **Reported separately and never mixed into the held-out test "
        "score** (`docs/DATASET.md`).",
        "",
        "The lead-time span column matters: a fresh workload covering a different span than the "
        "test split is not comparable to it. `ring_ood` trajectories differ only by a small "
        "centre offset, so their interval reflects within-workload repeatability rather than "
        "generalization spread.",
        "",
        "| Scenario | Run | Method | normMSE | 95% CI | lead time (h) | span matches training |",
        "|---|---|---|---:|---|---|---|",
        *rows,
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", type=Path, nargs="+", required=True)
    parser.add_argument("--split", default="test", choices=("validation", "test"))
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)

    text = build_report(args.runs, split=args.split)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
        print(f"wrote {args.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
